In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
a = (np.ones(20)*2)**np.arange(1,21)/np.arange(1,21)

a


array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
a = (np.ones(6)*0.1)**(3*np.arange(6))*(np.ones(6)*0.2)**(4*np.arange(6))
np.sum(a)

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
a = np.zeros((8, 8))
a[::2, ::2]= 1
a[1::2, 1::2]= 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))
r = (X[:,0]**2 + X[:,1]**2)**0.5
phi = np.arctan(X[:,1]/X[:,0])
print(r, phi)

[0.75477117 0.99111986 1.19564194 0.83280566 0.34702811] [1.23799828 1.06848808 0.77390585 0.09628007 1.35781791]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))
m = np.unravel_index(np.argmax(X), X.shape)
m



(9, 8)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [10]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
print(X)
print(y)
X[np.argmin((X.T[0]-X.T[1])**2 + (y[0][0]-y[0][1])**2)]


[[0.41285694 0.32277529]
 [0.80855878 0.66194002]
 [0.47986561 0.69175657]
 [0.94187515 0.45434766]
 [0.13558477 0.40830891]
 [0.51607141 0.848589  ]
 [0.12226798 0.26416771]
 [0.36768338 0.51802289]
 [0.37769663 0.80447417]
 [0.91237616 0.56691616]]
[[0.64655247 0.97549936]]


array([0.41285694, 0.32277529])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [11]:
x1 = np.arange(-3,4)
x1[:3] = x1[:3]**2+2*x1[:3]+6
x1[3:5]=x1[3:5] +6
x1[5:] = x1[5:]**2 + 4*x1[5:] -4
x1

array([ 9,  6,  5,  6,  7,  8, 17])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [12]:
X = np.random.random((10, 10))
np.mean(X - (np.ones((10,10))*np.mean(X, axis=1)), axis=1)




array([-0.15979776,  0.04076983, -0.00514984, -0.03025793,  0.18431035,
       -0.09320129,  0.09755534, -0.13965376,  0.07773696,  0.02768808])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [13]:
X = np.random.normal(loc=5, scale=2., size=1000)
X_= np.mean(X)
sig =  np.mean(X**2) - X_**2
X_, sig



(5.060817912368015, 3.985849258064448)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [14]:
A = np.arange(5)*np.ones((5,5))
A[1] =  np.roll(A[1], -1, axis = 0)
A[2] =  np.roll(A[2], -2, axis = 0)
A[3] =  np.roll(A[3], -3, axis = 0)
A[4] =  np.roll(A[4], -4, axis = 0)
A


array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [16]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 0, 2, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [17]:
def sample_1(x, c):
    assert len(x) > 0
    s = np.sum(x)
    res = np.repeat(np.cumsum(x),c).reshape((len(x), c)).astype("float32")
    val =s * np.random.random(c)
    res -=val
    res[res>=0]=1
    return  np.argmax(res, axis = 0)
            
sample_1([50, 3, 1, 7, 20], 5)   

array([0, 0, 0, 4, 0], dtype=int64)